
apiVersion: apps/v1
kind: Deployment
metadata:
  name: onnx-model-editor-deployment
  labels:
    app: onnx-model-editor
spec:
  replicas: 3
  selector:
    matchLabels:
      app: onnx-model-editor
  template:
    metadata:
      labels:
        app: onnx-model-editor
    spec:
      containers:
      - name: onnx-model-editor
        image: your_dockerhub_username/onnx_model_editor:latest
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_APP
          value: "app.py"
        - name: FLASK_ENV
          value: "production"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
