
apiVersion: v1
kind: Service
metadata:
  name: onnx-model-editor-service
spec:
  selector:
    app: onnx-model-editor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
